### ISSUE TITLE
Tag Creation Bug

### ISSUE THREAD

**Issue by RLFontan** [phase1geo/Journaler#4]
- Tag creation based on previously created tags isn't working.
- The tags appear as created, but when we get out of the date and come back, it just isn't there.

Elementary OS 7.1
Journaler 1.0.3

**Comment by phase1geo** [comment]
I think this may actually be an issue with auto-saving the entries that are written on previous days. This is an issue that I'm going to fix in the next release. If you want to test this out, try writing a back dated entry and hit Control-s to manually save the entry before selecting a different date and then see if the new tags exist or not.

**Comment by phase1geo** [comment]
I have committed a change to the main branch which should properly save an entry created on a day previous to the current date.  Feel free to pull from GitHub and test this out.
